# Generated by Django 6.0.6 on 2026-08-02 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.PositiveIntegerField(default=1)),
                ("xp", models.PositiveIntegerField(default=0)),
                ("coins", models.PositiveIntegerField(default=0)),
                ("streak_days", models.PositiveIntegerField(default=0)),
                ("last_activity_date", models.DateField(blank=True, null=True)),
                (
                    "education_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("school", "School"),
                            ("college", "College"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("board", models.CharField(blank=True, max_length=100, null=True)),
                ("medium", models.CharField(blank=True, max_length=50, null=True)),
                ("class_name", models.CharField(blank=True, max_length=20, null=True)),
                ("stream", models.CharField(blank=True, max_length=50, null=True)),
                ("university", models.CharField(blank=True, max_length=150, null=True)),
                ("branch", models.CharField(blank=True, max_length=100, null=True)),
                ("semester", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "goal_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("topper", "Topper"),
                            ("passing", "Just Passing"),
                            ("revision", "Revision"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("onboarding_completed", models.BooleanField(default=False)),
                ("bio", models.TextField(blank=True)),
                ("avatar_color", models.CharField(default="emerald", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
