# Generated by Django 6.0.6 on 2026-08-02 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_usertopicprogress"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("youtube", "YouTube"),
                            ("pdf", "PDF"),
                            ("article", "Article"),
                            ("mcq", "MCQ"),
                        ],
                        max_length=10,
                    ),
                ),
                ("platform", models.CharField(blank=True, max_length=100)),
                ("creator", models.CharField(blank=True, max_length=150)),
                ("url", models.URLField(blank=True)),
                ("duration", models.CharField(blank=True, max_length=50)),
                ("views", models.CharField(blank=True, max_length=20)),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
                ),
                ("difficulty", models.CharField(blank=True, max_length=10)),
                ("thumbnail_color", models.CharField(default="emerald", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="api.topic",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarked_by",
                        to="api.resource",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "resource")},
            },
        ),
    ]
