# Generated by Django 6.0.7 on 2026-08-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_studysession"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="daily_goal_minutes",
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name="profile",
            name="weekly_goal_minutes",
            field=models.PositiveIntegerField(default=420),
        ),
    ]
