# Generated by Django 6.0.7 on 2026-08-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_profile_daily_goal_minutes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="total_xp",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
