# Generated by Django 6.0.7 on 2026-08-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_chatmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="goal_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pass", "Pass Mode"),
                    ("average", "Average Mode"),
                    ("topper", "Topper Mode"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
