# Generated by Django 6.0.7 on 2026-08-06 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_quizattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
