# Generated by Django 6.0.7 on 2026-08-07 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_topic_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizattempt",
            name="is_mock_exam",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quiz_attempts",
                to="api.subject",
            ),
        ),
        migrations.AlterField(
            model_name="quizattempt",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quiz_attempts",
                to="api.topic",
            ),
        ),
    ]
