# Generated by Django 6.0.7 on 2026-08-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_quizattempt_is_mock_exam_quizattempt_subject_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="display_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
