# Generated by Django 6.0.7 on 2026-08-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_profile_display_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="display_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
